import { Poppins } from "next/font/google";
import "./globals.scss";
import Header from "./components/Global/Header";
import Footer from "./components/Global/Footer";

const inter = Poppins({ subsets: ["latin"],
weight: ['100','200','300','400','500','600','700','800','900'],
});

export const metadata = {
  title: "E Commerce App",
  description: "Generated by E Commerce App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
